package top.simba1949.webservice.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import top.simba1949.webservice.service.WSService;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-19T11:53:21.663+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "WSServiceImplService",
                  wsdlLocation = "http://localhost:8880/ws?wsdl",
                  targetNamespace = "http://impl.service.webservice.simba1949.top/")
public class WSServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.webservice.simba1949.top/", "WSServiceImplService");
    public final static QName WSServiceImplPort = new QName("http://impl.service.webservice.simba1949.top/", "WSServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8880/ws?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8880/ws?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WSServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WSService
     */
    @WebEndpoint(name = "WSServiceImplPort")
    public WSService getWSServiceImplPort() {
        return super.getPort(WSServiceImplPort, WSService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSService
     */
    @WebEndpoint(name = "WSServiceImplPort")
    public WSService getWSServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WSServiceImplPort, WSService.class, features);
    }

}
