
package top.simba1949.server.service.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import top.simba1949.server.service.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSService", targetNamespace = "http://service.server.simba1949.top/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSService {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIntValue", targetNamespace = "http://service.server.simba1949.top/", className = "top.simba1949.server.service.GetIntValue")
    @ResponseWrapper(localName = "getIntValueResponse", targetNamespace = "http://service.server.simba1949.top/", className = "top.simba1949.server.service.GetIntValueResponse")
    @Action(input = "http://service.server.simba1949.top/WSService/getIntValueRequest", output = "http://service.server.simba1949.top/WSService/getIntValueResponse")
    public int getIntValue(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.server.simba1949.top/", className = "top.simba1949.server.service.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.server.simba1949.top/", className = "top.simba1949.server.service.SayHelloResponse")
    @Action(input = "http://service.server.simba1949.top/WSService/sayHelloRequest", output = "http://service.server.simba1949.top/WSService/sayHelloResponse")
    public String sayHello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getList", targetNamespace = "http://service.server.simba1949.top/", className = "top.simba1949.server.service.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://service.server.simba1949.top/", className = "top.simba1949.server.service.GetListResponse")
    @Action(input = "http://service.server.simba1949.top/WSService/getListRequest", output = "http://service.server.simba1949.top/WSService/getListResponse")
    public List<String> getList();

}
