package top.simba1949.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-17T13:43:20.541+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://webservice.simba1949.top/", name = "HelloWorldService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldService {

    @WebMethod
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://webservice.simba1949.top/", className = "top.simba1949.webservice.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://webservice.simba1949.top/", className = "top.simba1949.webservice.SayHiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String sayHi(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
