package top.simba1949.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-19T11:16:45.052+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://service.webservice.simba1949.top/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "getString", targetNamespace = "http://service.webservice.simba1949.top/", className = "top.simba1949.webservice.service.GetString")
    @ResponseWrapper(localName = "getStringResponse", targetNamespace = "http://service.webservice.simba1949.top/", className = "top.simba1949.webservice.service.GetStringResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getString();
}
