package top.simba1949.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-19T14:17:23.105+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://service.webservice.simba1949.top/", name = "WSService")
@XmlSeeAlso({ObjectFactory.class})
public interface WSService {

    @WebMethod
    @RequestWrapper(localName = "getString", targetNamespace = "http://service.webservice.simba1949.top/", className = "top.simba1949.webservice.service.GetString")
    @ResponseWrapper(localName = "getStringResponse", targetNamespace = "http://service.webservice.simba1949.top/", className = "top.simba1949.webservice.service.GetStringResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getString(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
